# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/fraud_detection/fraud_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'utils/pb/fraud_detection/fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.utils/pb/fraud_detection/fraud_detection.proto\x12\x0f\x66raud_detection\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\"9\n\x0c\x46raudRequest\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\t\x12\x14\n\x0corder_amount\x18\x02 \x01(\x02\"!\n\rFraudResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x32Y\n\x0cHelloService\x12I\n\x08SayHello\x12\x1d.fraud_detection.HelloRequest\x1a\x1e.fraud_detection.HelloResponse2d\n\x15\x46raudDetectionService\x12K\n\nCheckFraud\x12\x1d.fraud_detection.FraudRequest\x1a\x1e.fraud_detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.fraud_detection.fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=67
  _globals['_HELLOREQUEST']._serialized_end=95
  _globals['_HELLORESPONSE']._serialized_start=97
  _globals['_HELLORESPONSE']._serialized_end=130
  _globals['_FRAUDREQUEST']._serialized_start=132
  _globals['_FRAUDREQUEST']._serialized_end=189
  _globals['_FRAUDRESPONSE']._serialized_start=191
  _globals['_FRAUDRESPONSE']._serialized_end=224
  _globals['_HELLOSERVICE']._serialized_start=226
  _globals['_HELLOSERVICE']._serialized_end=315
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=317
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
