# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_queue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"(\n\x0fQueueAddRequest\x12\x15\n\raddable_order\x18\x01 \x01(\t\"-\n\x12QueueRemoveRequest\x12\x17\n\x0fremovable_order\x18\x01 \x01(\t\"5\n\rQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0border_queue\x18\x02 \x03(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2\xa0\x01\n\x11OrderQueueService\x12\x43\n\x07\x45nqueue\x12\x1c.order_queue.QueueAddRequest\x1a\x1a.order_queue.QueueResponse\x12\x46\n\x07\x44\x65queue\x12\x1f.order_queue.QueueRemoveRequest\x1a\x1a.order_queue.QueueResponse2Q\n\x0cHelloService\x12\x41\n\x08SayHello\x12\x19.order_queue.HelloRequest\x1a\x1a.order_queue.HelloResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUEUEADDREQUEST']._serialized_start=34
  _globals['_QUEUEADDREQUEST']._serialized_end=74
  _globals['_QUEUEREMOVEREQUEST']._serialized_start=76
  _globals['_QUEUEREMOVEREQUEST']._serialized_end=121
  _globals['_QUEUERESPONSE']._serialized_start=123
  _globals['_QUEUERESPONSE']._serialized_end=176
  _globals['_HELLOREQUEST']._serialized_start=178
  _globals['_HELLOREQUEST']._serialized_end=206
  _globals['_HELLORESPONSE']._serialized_start=208
  _globals['_HELLORESPONSE']._serialized_end=241
  _globals['_ORDERQUEUESERVICE']._serialized_start=244
  _globals['_ORDERQUEUESERVICE']._serialized_end=404
  _globals['_HELLOSERVICE']._serialized_start=406
  _globals['_HELLOSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
