# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\xeb\x02\n\x13VerificationRequest\x12\x31\n\x05items\x18\x01 \x03(\x0b\x32\".transaction_verification.ItemData\x12,\n\x04user\x18\x02 \x01(\x0b\x32\x1e.transaction_verification.User\x12\x38\n\ncreditCard\x18\x03 \x01(\x0b\x32$.transaction_verification.CreditCard\x12\x32\n\x07\x63omment\x18\x04 \x01(\x0b\x32!.transaction_verification.Comment\x12@\n\x0e\x62illingAddress\x18\x05 \x01(\x0b\x32(.transaction_verification.BillingAddress\x12\x16\n\x0eshippingMethod\x18\x06 \x01(\t\x12\x14\n\x0cgiftWrapping\x18\x07 \x01(\x08\x12\x15\n\rtermsAccepted\x18\x08 \x01(\x08\"I\n\x14VerificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x07\x63omment\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_comment\"*\n\x08ItemData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\t\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"\x1a\n\x07\x43omment\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2\x94\x01\n\x1eTransactionVerificationService\x12r\n\x11VerifyTransaction\x12-.transaction_verification.VerificationRequest\x1a..transaction_verification.VerificationResponse2k\n\x0cHelloService\x12[\n\x08SayHello\x12&.transaction_verification.HelloRequest\x1a\'.transaction_verification.HelloResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=61
  _globals['_VERIFICATIONREQUEST']._serialized_end=424
  _globals['_VERIFICATIONRESPONSE']._serialized_start=426
  _globals['_VERIFICATIONRESPONSE']._serialized_end=499
  _globals['_ITEMDATA']._serialized_start=501
  _globals['_ITEMDATA']._serialized_end=543
  _globals['_USER']._serialized_start=545
  _globals['_USER']._serialized_end=582
  _globals['_CREDITCARD']._serialized_start=584
  _globals['_CREDITCARD']._serialized_end=649
  _globals['_COMMENT']._serialized_start=651
  _globals['_COMMENT']._serialized_end=677
  _globals['_BILLINGADDRESS']._serialized_start=679
  _globals['_BILLINGADDRESS']._serialized_end=770
  _globals['_HELLOREQUEST']._serialized_start=772
  _globals['_HELLOREQUEST']._serialized_end=800
  _globals['_HELLORESPONSE']._serialized_start=802
  _globals['_HELLORESPONSE']._serialized_end=835
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=838
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=986
  _globals['_HELLOSERVICE']._serialized_start=988
  _globals['_HELLOSERVICE']._serialized_end=1095
# @@protoc_insertion_point(module_scope)
