# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"!\n\x0ePrepareRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\" \n\rCommitRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x0c\x41\x62ortRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xd6\x01\n\x0ePaymentService\x12\x43\n\x0ePreparePayment\x12\x17.payment.PrepareRequest\x1a\x18.payment.PrepareResponse\x12@\n\rCommitPayment\x12\x16.payment.CommitRequest\x1a\x17.payment.CommitResponse\x12=\n\x0c\x41\x62ortPayment\x12\x15.payment.AbortRequest\x1a\x16.payment.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=26
  _globals['_PREPAREREQUEST']._serialized_end=59
  _globals['_PREPARERESPONSE']._serialized_start=61
  _globals['_PREPARERESPONSE']._serialized_end=93
  _globals['_COMMITREQUEST']._serialized_start=95
  _globals['_COMMITREQUEST']._serialized_end=127
  _globals['_COMMITRESPONSE']._serialized_start=129
  _globals['_COMMITRESPONSE']._serialized_end=162
  _globals['_ABORTREQUEST']._serialized_start=164
  _globals['_ABORTREQUEST']._serialized_end=195
  _globals['_ABORTRESPONSE']._serialized_start=197
  _globals['_ABORTRESPONSE']._serialized_end=229
  _globals['_PAYMENTSERVICE']._serialized_start=232
  _globals['_PAYMENTSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
