# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import executor_pb2 as executor__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLeaderElection = channel.unary_unary(
                '/executor.ExecutorService/StartLeaderElection',
                request_serializer=executor__pb2.LeaderElectionRequest.SerializeToString,
                response_deserializer=executor__pb2.LeaderElectionResponse.FromString,
                _registered_method=True)
        self.ElectLeader = channel.unary_unary(
                '/executor.ExecutorService/ElectLeader',
                request_serializer=executor__pb2.LeaderElectionRequest.SerializeToString,
                response_deserializer=executor__pb2.LeaderElectionResponse.FromString,
                _registered_method=True)
        self.AnnounceLeader = channel.unary_unary(
                '/executor.ExecutorService/AnnounceLeader',
                request_serializer=executor__pb2.LeaderElectionRequest.SerializeToString,
                response_deserializer=executor__pb2.LeaderElectionResponse.FromString,
                _registered_method=True)


class ExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartLeaderElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartLeaderElection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLeaderElection,
                    request_deserializer=executor__pb2.LeaderElectionRequest.FromString,
                    response_serializer=executor__pb2.LeaderElectionResponse.SerializeToString,
            ),
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=executor__pb2.LeaderElectionRequest.FromString,
                    response_serializer=executor__pb2.LeaderElectionResponse.SerializeToString,
            ),
            'AnnounceLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLeader,
                    request_deserializer=executor__pb2.LeaderElectionRequest.FromString,
                    response_serializer=executor__pb2.LeaderElectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.ExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.ExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartLeaderElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.ExecutorService/StartLeaderElection',
            executor__pb2.LeaderElectionRequest.SerializeToString,
            executor__pb2.LeaderElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.ExecutorService/ElectLeader',
            executor__pb2.LeaderElectionRequest.SerializeToString,
            executor__pb2.LeaderElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.ExecutorService/AnnounceLeader',
            executor__pb2.LeaderElectionRequest.SerializeToString,
            executor__pb2.LeaderElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HelloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/executor.HelloService/SayHello',
                request_serializer=executor__pb2.HelloRequest.SerializeToString,
                response_deserializer=executor__pb2.HelloResponse.FromString,
                _registered_method=True)


class HelloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=executor__pb2.HelloRequest.FromString,
                    response_serializer=executor__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.HelloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.HelloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.HelloService/SayHello',
            executor__pb2.HelloRequest.SerializeToString,
            executor__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
